### ISSUE TITLE
Install `rdkit` from pip

### ISSUE THREAD

**Issue by lukasturcani** [JelfsMaterialsGroup/stko#148]
Given that `stk` now installs `rdkit` from `pip` I think that it is potentially dangerous to encourage users to install `rdkit` via conda in the readme. This could end up with them having two versions of `rdkit` installed. I think `rdkit` pip should be used as the requirement for simplicity and consistency.

**Comment by lukasturcani** [comment]
In addition, the line `install stk` from pip in the README is redundant. `stk` is listed as an explicit dependency in `setup.py` and should therefore be installed automatically when a user install `stko` there is no need for them to run the `pip install stk` command themselves.

**Comment by andrewtarzia** [comment]
TY @lukasturcani
