### ISSUE TITLE
Error in documentation -- stko/utilities/utilities.py

### ISSUE THREAD

**Issue by austin-mroz** [JelfsMaterialsGroup/stko#153]
The documentation for the `MAEExtractor` method `lowest_energy_conformer() `[starting **line 184**] is incorrect.

The returned tuple is ordered as [(energy, index)], not [(index, energy)] as is listed in the documentation.

Propose modifying **line 200** to `returned = [(123.1, 23), (143.89, 1), (150.6, 12), ...]`

and modifying **lines 202 - 203** to 

```
Where each :class:`tuple` holds the energy of the
`n` lowest energy conformers and the id, respectively.
```

Issue identified by @lukasturcani

**Comment by andrewtarzia** [comment]
Done as proposed.
