### ISSUE TITLE
Calculate energy with orca Issue

### ISSUE THREAD

**Issue by Joe-Anslow** [JelfsMaterialsGroup/stko#176]
**when using the below code:**

```python
orca = stko.OrcaEnergy(
    orca_path='/home/cmja2/orca',
    output_dir='./Polymer2_ORCA',
    topline='! SP B97-3c',
    write_input_only=False,
    discard_output=False,
)

orca.get_results(polymer)
```
**this error occurs:**

```
  File "/home/cmja2/anaconda3/lib/python3.11/site-packages/stko/_internal/calculators/orca_calculators.py", line 202, in _check_outcome
    if "****ORCA TERMINATED NORMALLY****" not in lines[-2]:
                                                 ~~~~~^^^^
IndexError: list index out of range
```

I think that maybe orca itself was at fault and I ran the orca input indendently which was successful. When using stko, the output file is there but is empty. This would mean there is no line -2. could it be that stko is not waiting for the orca run to finish before looking at line -2? The error with orca does happen almost immediately whilst the orca calculation itself takes around a couple of minutes.

**Comment by andrewtarzia** [comment]
Editted to include code formatting

**Comment by andrewtarzia** [comment]
If we solve this, also make OrcaExtractor public facing

**Comment by andrewtarzia** [comment]
I seem to be able to have jobs run with this:
```python
calculator = stko.OrcaEnergy(
                    orca_path=orca_path,
                    topline="! SP B97-3c",
                    num_cores=8,
                    charge=charge,
                    multiplicity=1,
                    discard_output=True,
                    output_dir=calculation_path,
                )
```

**Comment by Joe-Anslow** [comment]
Implementing the above code produces the same error:

**Input:** 

```python
import stk
import stko

bb1 = stk.BuildingBlock('NCCNCCN', [stk.PrimaryAminoFactory()])
bb2 = stk.BuildingBlock('O=CCCC=O', [stk.AldehydeFactory()])
polymer = stk.ConstructedMolecule(
    stk.polymer.Linear(
        building_blocks=(bb1, bb2),
        repeating_unit="AB",
        orientations=[0, 0],
        num_repeating_units=1
    )
)

# Optimize the constructed molecule so that it has a
# reasonable structure.
opt = stko.UFF()
polymer = opt.optimize(polymer)

calculator = stko.OrcaEnergy(
                    orca_path='/home/cmja2/orca',
                    topline="! SP B97-3c",
                    num_cores=1,
                    charge=0,
                    multiplicity=1,
                    discard_output=False,
                    output_dir='./output'
                )

orca_results = calculator.get_results(polymer)

# Extract properties from the energy calculator for a given
# molecule.
total_energy = orca_results.get_total_energy()
``` 
**Output:**

Traceback (most recent call last):
  File "/home/cmja2/stk/STK_Calculations/Orca-Tests/Test.py", line 30, in <module>
    orca_results = calculator.get_results(polymer)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmja2/anaconda3/lib/python3.11/site-packages/stko/_internal/calculators/orca_calculators.py", line 325, in get_results
    return OrcaResults(
           ^^^^^^^^^^^^
  File "/home/cmja2/anaconda3/lib/python3.11/site-packages/stko/_internal/calculators/results/orca_results.py", line 19, in __init__
    next(generator)  # type: ignore[call-overload]
    ^^^^^^^^^^^^^^^
  File "/home/cmja2/anaconda3/lib/python3.11/site-packages/stko/_internal/calculators/orca_calculators.py", line 288, in calculate
    self._run_orca(
  File "/home/cmja2/anaconda3/lib/python3.11/site-packages/stko/_internal/calculators/orca_calculators.py", line 266, in _run_orca
    self._check_outcome(out_file)
  File "/home/cmja2/anaconda3/lib/python3.11/site-packages/stko/_internal/calculators/orca_calculators.py", line 202, in _check_outcome
    if "****ORCA TERMINATED NORMALLY****" not in lines[-2]:
                                                 ~~~~~^^^^
IndexError: list index out of range

**Comment by Joe-Anslow** [comment]
Orca input file can be run fine manually

**Comment by andrewtarzia** [comment]
I foolishly never asked what version of orca you are running?

**Comment by Joe-Anslow** [comment]
I'm running Program Version 5.0.4 - Release

**Comment by andrewtarzia** [comment]
* conda/mamba create new env with Python 3.11
* stk-2024.3.28.0
* stko-2023.11.13.0
* Orca 6.0.0

With that process for a new environment, your code runs perfectly fine for me.

[output.txt](https://github.com/user-attachments/files/16508750/output.txt)

I have noticed that Orca 5 requires more detailed environment variables to be set for it to run. Is it possible that the python environment removes some of those variables?

**Comment by Joe-Anslow** [comment]
Created new conda environment:

stk - 2024.3.28.0              
stko- -2023.11.13.0
orca program Version 6.0.0 - RELEASE -

Same error. Orca and stk both work individually.

There must be a difference in my conda env list? I only pip installed stk, stko, xtb and openbabel

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
atomlite                  4.4.5                    pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dftd4                     3.6.0                hf49bc11_0    conda-forge
dill                      0.3.8                    pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
expat                     2.6.2                h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
icu                       75.1                 he02047a_0    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.80.3               h8a4344b_1    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
matplotlib                3.9.0                    pypi_0    pypi
mchammer                  2024.2.29.0              pypi_0    pypi
mctc-lib                  0.3.1                h74f4db8_0    conda-forge
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.5                  h59595ed_0    conda-forge
networkx                  3.3                      pypi_0    pypi
numpy                     2.0.1                    pypi_0    pypi
openbabel                 3.1.1           py311h8b422cb_9    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pathos                    0.3.2                    pypi_0    pypi
pcre2                     10.44                h0f59acf_0    conda-forge
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
polars                    1.4.1                    pypi_0    pypi
pox                       0.3.4                    pypi_0    pypi
ppft                      1.7.6.8                  pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pymongo                   4.8.0                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1                   pypi_0    pypi
rdkit                     2024.3.4                 pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.14.0                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
simple-dftd3              1.0.0                hd59d2e7_0    conda-forge
six                       1.16.0                   pypi_0    pypi
spindry                   2024.2.29.0              pypi_0    pypi
stk                       2024.3.28.0              pypi_0    pypi
stko                      2023.11.13.0             pypi_0    pypi
tblite                    0.3.0                hf49bc11_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml-f                    0.4.2                hd8f1df9_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
vabene                    0.0.5                    pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xtb                       6.6.1                hf49bc11_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.3.1                h4ab18f5_1    conda-forge

**Comment by Joe-Anslow** [comment]
orca_energy.output file is created but blank

**Comment by andrewtarzia** [comment]
Does that happen instantly? Or does it look like a calculation is running (i.e. is your CPU at 100%, does it take as long  as running it manually?)

**Comment by Joe-Anslow** [comment]
Orca doesn't appear to be running. It does not show up on the system monitor. CPU usage spikes equally with the orca code removed.

**Comment by andrewtarzia** [comment]
Ok, this is all very strange. If you can modify the stko source code to and try and get `sp.call` to provide more information in the function `_run_orca` here: https://github.com/JelfsMaterialsGroup/stko/blob/master/src/stko/_internal/calculators/orca_calculators.py then maybe we can diagnose this issue. Currently, I am at a loss. It seems system specific, but not like an Orca issue because the manual jobs run.

**Comment by Joe-Anslow** [comment]
I'll have a look. Thankyou for your help so far :)

**Comment by Joe-Anslow** [comment]
I've ran the orca job seperately, Then added a time.sleep command, pasting the complete output file into the correct folder. everything else runs fine. It must be that orca is not running for some reason

**Comment by Joe-Anslow** [comment]
I've found the issue. In the code:
```
calculator = stko.OrcaEnergy(
                    orca_path='/home/cmja2/orca_6_0_0',
                    topline="! SP B97-3c",
                    num_cores=1,
                    charge=0,
                    multiplicity=1,
                    discard_output=False,
                    output_dir='./output'
                )
```

The orca_path needs to be changed to '/home/cmja2/orca_6_0_0/orca',
The original path does not flag the PathError so I didn't look at that initially! easy solution in the end...

**Comment by andrewtarzia** [comment]
Ahhh excellent you found the solution. We will try and make that exception clearer!
