### ISSUE TITLE
Fix _fix_distances function in macromodel.py

### ISSUE THREAD

**Issue by stevenkbennett** [JelfsMaterialsGroup/stko#40]
Currently `_fix_distances` fixes bonds created by stk. It should be the opposite

**Comment by andrewtarzia** [comment]
@stevenkbennett  I know this was a long time ago, but I assume the code is not currently broken otherwise everything would be pretty messed up?

**Comment by stevenkbennett** [comment]
Yes, this was mainly a confusion in the naming of the function argument. I think it can be closed.
